# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sparktype < Formula
  desc "Generate static types from OpenAPI specifications"
  homepage "https://github.com/hntrl/sparktype"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hntrl/sparktype/releases/download/v0.1.2/sparktype_0.1.2_darwin_amd64.tar.gz"
      sha256 "805f90bceac5af8985fa038e5ec5f67c14c7c43c7c273b5ca1f1cf71ca4e26b0"

      def install
        bin.install "sparktype"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hntrl/sparktype/releases/download/v0.1.2/sparktype_0.1.2_darwin_arm64.tar.gz"
      sha256 "d07dd55950cbae1ca1264e74e49684cbee3d641f9f2bf97f8e9333008179cc4b"

      def install
        bin.install "sparktype"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hntrl/sparktype/releases/download/v0.1.2/sparktype_0.1.2_linux_amd64.tar.gz"
      sha256 "b97ad9af1024744d3eb02a77055cfa146dae4ed482e7b7ddfa7158cc4d899d50"
      def install
        bin.install "sparktype"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hntrl/sparktype/releases/download/v0.1.2/sparktype_0.1.2_linux_arm64.tar.gz"
      sha256 "885a0a5a5cfc0f4d2fd78b59779092c1d94d7f0f7a61ce35968ed5ab93c60160"
      def install
        bin.install "sparktype"
      end
    end
  end

  test do
    system "#{bin}/sparktype", "--help"
  end
end
