# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sparktype < Formula
  desc "Generate static types from OpenAPI specifications"
  homepage "https://github.com/hntrl/sparktype"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hntrl/sparktype/releases/download/v0.1.3/sparktype_0.1.3_darwin_amd64.tar.gz"
      sha256 "0c508a920b64a5b1a3064090970eb0616fc3237e9c593ea8b25c8def9fd5ff6c"

      def install
        bin.install "sparktype"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hntrl/sparktype/releases/download/v0.1.3/sparktype_0.1.3_darwin_arm64.tar.gz"
      sha256 "4f475f073d77222bf3b7aee295796e5fc30cb48aada3479612c5e0786981c5f6"

      def install
        bin.install "sparktype"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hntrl/sparktype/releases/download/v0.1.3/sparktype_0.1.3_linux_amd64.tar.gz"
      sha256 "25d40fd7a08c098496c192ace0a16fd4cf4bd7b6dd2172ed8aea4916a61d2e96"
      def install
        bin.install "sparktype"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hntrl/sparktype/releases/download/v0.1.3/sparktype_0.1.3_linux_arm64.tar.gz"
      sha256 "43a2e885d2c93b7553c6355c8f33fa769e9371655ff961285746a8d1fff58c24"
      def install
        bin.install "sparktype"
      end
    end
  end

  test do
    system "#{bin}/sparktype", "--help"
  end
end
