# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sparktype < Formula
  desc "Generate static types from OpenAPI specifications"
  homepage "https://github.com/hntrl/sparktype"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hntrl/sparktype/releases/download/v0.1.0/sparktype_0.1.0_darwin_amd64.tar.gz"
      sha256 "d98a32a52a223c6f940b2bb598b3e10c1825a96430f1e3e28cc71c82a0b74f17"

      def install
        bin.install "sparktype"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hntrl/sparktype/releases/download/v0.1.0/sparktype_0.1.0_darwin_arm64.tar.gz"
      sha256 "6274fad143296b171097aea0992b29370b84061cc3f348b0c10fff34e78ec4c2"

      def install
        bin.install "sparktype"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hntrl/sparktype/releases/download/v0.1.0/sparktype_0.1.0_linux_amd64.tar.gz"
      sha256 "e7596b925da8c4cccd22d025319ef82008e6b7417cbbb96322c59c4aa5a47f99"
      def install
        bin.install "sparktype"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hntrl/sparktype/releases/download/v0.1.0/sparktype_0.1.0_linux_arm64.tar.gz"
      sha256 "380816ea20acb76fd16853fdf774a106b71a72d9b1661c83e3201102bf096cc8"
      def install
        bin.install "sparktype"
      end
    end
  end

  test do
    system "#{bin}/sparktype", "--help"
  end
end
